@baseUrl = http://localhost:3001
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiUmFmYWVsQGVtYWlsLmNvbS5iciIsImlhdCI6MTc3NTE1Mjg4MCwiZXhwIjoxNzc1MTg4ODgwfQ.NeyiCJI_pLidzRr7CMVBkfK_g_Nq4ws44sZzOF2EELQ

###
//SERVIDOR DE TESTE, PARA VER SE ESTÁ ON!
GET http://localhost:3001/health HTTP/1.1

###
//CADASTRAR USUÁRIO
POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
  "name": "Rafael",
  "email": "Rafael@email.com.br",
  "password": "senha123",
  "role": "DEFAULT"
}


////////////////////    USA O TOKEN        ///////////////////////


###
//LOGIN DO USUARIO
POST http://localhost:3001/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "Rafael@email.com.br",
  "password": "senha123"
}


###
//MOSTRA TODOS OS USUARIOS
GET http://localhost:3001/users HTTP/1.1
Authorization: Bearer {{token}}


###
//MOSTRA USUARIO POR ID
GET http://localhost:3001/users/1 HTTP/1.1
Authorization: Bearer {{token}}


###
//ATUALIZA O USUARIO PELO ID /2
PUT http://localhost:3001/users/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Miles",
  "email": "miles@email.com",
  "password": "senha123"
}

###
//DELETA O USUARIO PELO ID
DELETE http://localhost:3001/users/8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}




////////////////////////
//////  TAREFAS ////////
////////////////////////


###
//CRIAR TAREFA
POST http://localhost:3001/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Estudar Node.js",
  "content": "Aprender sobre validação do Prisma",
  "userId": 1
}

###
//LISTAR TAREFAS DO USUÁRIO
GET http://localhost:3001/posts/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###
//LISTA A TAREFAS DE TODOS OS USUARIOS
GET http://localhost:3001/posts HTTP/1.1
Authorization: Bearer {{token}}


###
//ATUALIZAR TAREFA
PUT http://localhost:3001/posts/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1,
  "task": "Estudar Node.js e Express",
  "finished": true
}

###
//DELETAR TAREFA
DELETE http://localhost:3001/posts/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1
}
